# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('socios', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=2)),
                ('puesto', models.CharField(max_length=4)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Equipos')),
            ],
        ),
    ]
