# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_auto_20170217_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='nacionalidad',
            field=models.CharField(default='Espanola', max_length=50),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='num_partidos',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
