# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_auto_20170218_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='foto',
            field=models.CharField(default='/static/pagina/no_foto.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='foto',
            field=models.CharField(default='/static/pagina/noticias/no_foto.png', max_length=100),
        ),
    ]
