# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_auto_20170218_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=50)),
                ('historia', models.CharField(default='historia', max_length=5000)),
                ('foto', models.CharField(default='/static/pagina/simbolos/no_foto.png', max_length=100)),
            ],
        ),
    ]
